name: Jupyynterest
volumes:
  db-data:
networks:
  backend:

services:
  jupyynterest-db:
    image: 'postgres:15'
    container_name: jupyynterest-db
    restart: always
    ports:
      - 5456:5432
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jupyynterest
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend
